
--Create database
--CREATE DATABASE ACCOUNTING
--go

CREATE TABLE [dbo].[Klijent](
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IME NVARCHAR(50) NOT NULL,
	PREZIME NVARCHAR(50) NOT NULL,
	TELEFON CHAR(25) NOT NULL,
	MAIL NVARCHAR(100) NOT NULL,
	NAZVIV_FIRME NVARCHAR(100) NOT NULL,
	PIB CHAR(13) NOT NULL,
)

SELECT * FROM Klijent
